article/urls.py
# 作者: hxd
# 2023年06月02日18时55分04秒
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    # 写文章
    path('article-create/', views.article_create, name='article_create'),
    # 展示文章详情
    path('article-detail-show/<int:id>/', views.article_detail, name='article_detail_show'),
    # 删除文章
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),

    path('article-list/',views.view,name = 'article_list'),

    path('show_articles_page_by_type/',views.show_articles_page_by_type,name = 'show_articles_page_by_type'),

    path('happen/', views.article_list, {'type': 'happen'}, name='happen'),
    path('prevent/', views.article_list, {'type': 'prevent'}, name='prevent'),
    path('appliance/', views.article_list,  {'type': 'appliance'},name='appliance'),
    path('news/', views.article_list,  {'type': 'news'},name='news'),
    path('about/', views.article_list,  {'type': 'about'},name='about'),
    # 更新文章
    path('article-update/<int:id>/', views.article_update, name='article_update'),

]

mysite2/urls.py
from django.contrib import admin
from django.urls import path,include
from article.views import view
urlpatterns = [
    path('', view,name='home'),
    path('admin/',admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),

    path(r'mdeditor/', include('mdeditor.urls')),
]

userprofile/urls.py
# 作者: hxd
# 2023年07月03日17时46分05秒
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户信息
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
import django.utils.timezone as timezone
from django.contrib.auth.models import User
from django.db import models
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
# Create your models here.
from mdeditor.fields import MDTextField


class NavBar(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    parent_id = models.IntegerField(blank=True, null=True)
    sort = models.IntegerField()




class ArticleColumn(models.Model):
    """
    栏目的 Model
    """
    # 栏目标题
    title = models.CharField(max_length=100, blank=True)
    # 创建时间
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Post(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=100)
    # 文章作者。参数 on_delete 用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    total_views = models.PositiveIntegerField(default=0)
    content = MDTextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # 文章栏目的 “一对多” 外键
    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )
    # 内部类 class Meta 用于给 model 定义元数据
    class Meta:
        # ordering 指定模型返回的数据的排列顺序
        # '-created' 表明数据应该以倒序排列
        ordering = ('-created_at',)

    # 函数 __str__ 定义当调用对象的 str() 方法时的返回值内容
    def __str__(self):
        # return self.title 将文章标题返回
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        print("调用了获取文章地址的方法")
        return reverse('article:article_detail_show', args=[self.id])

article/forms.py
# 作者: hxd
# 2023年06月02日19时21分51秒

# 引入表单类
from django import forms
# 引入文章模型
from .models import Post

# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = Post
        # 定义表单包含的字段
        fields = ('title','content')

article/views.py
from django.shortcuts import render,redirect
from django.template import RequestContext

from comment.models import Comment
from .models import NavBar,Post,ArticleColumn
# 引入HttpResponse
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlePostForm
from django.contrib.auth.models import User
# 引入markdown模块
import markdown
from django.core.paginator import Paginator
# Create your views here.
def show_article_list():
    # 查询发布的文章
    article_list = Post.objects.all()
    # 将文章按照模块分类
    happen_article_list = []  # 近视的发生
    prevent_article_list = []  # 近视的预防
    appliance_article_list = []  # 防近视的器材
    news_article_list = []  # 防近视要闻
    for item in article_list:
        if item.column.title == "防近视要闻":
            news_article_list.append(item)
        elif item.column.title == "防近视器材":
            appliance_article_list.append(item)
        elif item.column.title == "近视的预防":
            prevent_article_list.append(item)
        elif item.column.title == "近视的发生":
            happen_article_list.append(item)

    # 最多只显示前8条数据
    happen_article_list_len = len(happen_article_list) if len(happen_article_list) <= 8 else 8
    prevent_article_list_len = len(prevent_article_list) if len(prevent_article_list) <= 8 else 8
    appliance_article_list_len = len(appliance_article_list) if len(appliance_article_list) <= 8 else 8
    news_article_list_len = len(news_article_list) if len(news_article_list) <= 8 else 8
    happen_article_sub_list = happen_article_list[:happen_article_list_len]
    prevent_article_sub_list = prevent_article_list[:prevent_article_list_len]
    appliance_article_sub_list = appliance_article_list[:appliance_article_list_len]
    news_article_sub_list = news_article_list[:news_article_list_len]
    return [happen_article_sub_list,prevent_article_sub_list,appliance_article_sub_list,news_article_sub_list]
# 获取Nav_bar
def view(request):
    happen_article_sub_list,prevent_article_sub_list,appliance_article_sub_list,news_article_sub_list = show_article_list()
    return render(request, "home.html", {"happen_article_sub_list":happen_article_sub_list,
                                         "prevent_article_sub_list": prevent_article_sub_list,
                                         "appliance_article_sub_list": appliance_article_sub_list,
                                         "news_article_sub_list": news_article_sub_list})


def article_detail(request,id):
    if request.user.is_authenticated:
        logged_in = True
        username = request.session.get('username', None)
    else:
        logged_in = False
        username = '请登录：'
    # 查询所有导航栏分类
    nav_bar_list = ArticleColumn.objects.all()
    # 取出相应的文章
    article = Post.objects.get(id=id)

    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])

    author_name = User.objects.get(id = article.author_id)
    # 将markdown语法渲染成html样式
    article.content = markdown.markdown(article.content.replace("\r\n", '  \n'),
                                        extensions=[
                                            'markdown.extensions.extra',
                                            'markdown.extensions.codehilite',
                                            'markdown.extensions.toc',],
                                        safe_mode = True,
                                        enable_attributes=False)
    #取出文章评论
    comments_list = Comment.objects.filter(article=id)

    # 每页显示 5条评论
    paginator = Paginator(comments_list, 5)

    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给 articles
    comments = paginator.get_page(page)


    return render(request, "article.html",{"article":article,
                                           "username": username,
                                           "logged_in": logged_in,
                                           "author":author_name,
                                           'comments_list':comments_list,
                                           'comments': comments,
                                           'nav_bar_list':nav_bar_list})

def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            # 指定目前登录的用户为作者
            new_article.author = User.objects.get(id=request.user.id)
            # 新增的代码
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            return redirect("/")
        else:
            for field in article_post_form:
                for error in field.errors:
                    # 显示错误信息
                    print(field.label, error)
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 新增及修改的代码
        columns = ArticleColumn.objects.all()
        # 赋值上下文
        context = {'article_post_form': article_post_form,'columns':columns}
        # 返回模板
        return render(request, 'editor.html', context)

# 删文章
def article_delete(request, id):
    # 根据 id 获取需要删除的文章
    article = Post.objects.get(id=id)
    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    return redirect("article:article_list")

def show_articles_page_by_type(request):
    # 获取文章的id
    id = request.GET.get("id")

    # 查询所有导航栏分类
    nav_bar_list = ArticleColumn.objects.all()
    # 查询发布的文章
    article_list = Post.objects.filter(column_id=id)
    # 每页显示 1 篇文章
    paginator = Paginator(article_list, 15)
    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)

    # 赋值上下文
    context = {"nav_bar_list":nav_bar_list,
               'article_list': articles}
    # 返回模板
    return render(request, 'article_list.html', context)



def article_list(request,type):
    if type == 'home':
        pass
    # 返回主页
    elif type == 'happen':
        article_list = Post.objects.filter(column_id=1)
    elif type == 'prevent':
        article_list = Post.objects.filter(column_id=2)
    elif type == 'appliance':
        article_list = Post.objects.filter(column_id=3)
    elif type == 'news':
        article_list = Post.objects.filter(column_id=4)
    else:
        pass
    # 每页显示 1 篇文章
    paginator = Paginator(article_list, 1)
    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)
    # 赋值上下文
    context = {'articles': articles}
    # 返回模板
    return render(request, 'article_list.html', context)


def article_update(request,id):
    article = Post.objects.get(id=id)
    if request.method == "POST":
        article_post_form = ArticlePostForm(data = request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.content = request.POST['content']
            article.save()
            return redirect("article:article_detail_show",id=id)
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 文章分类
        columns = ArticleColumn.objects.all()
        type = columns[article.column_id].title
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = {'article': article,
                   'article_post_form': article_post_form,
                   'columns':columns,
                   "type":type}
        # 将响应返回到模板中
        return render(request, 'editor.html', context)

templates/article_detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-success">
            <p>作者：{{ article.author }}删除文章</p>

        </div>
         <!-- 文章正文 -->
        <div class="col-12">

            <p>{{ article.content }}</p>
        </div>
    </div>
    <hr color="green">
    <!-- 发表评论 -->
        {% if user.is_authenticated %}
    <br>
        {% else %}
    <br>
    <h5 class="row justify-content-center">
        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
    </h5>
    <br>
    {% endif %}
        <!-- 显示评论 -->
    {% if len %}
    
    {% endif %} 
    <h4>共有{{ comments.count }}条评论</h4>
    <div class="row">
        {% for comment in comments %}
            <hr>
            <p>
                <strong style="color: pink">
                    {{ comment.user }}
                </strong> 于
                <span style="color: green">
                    {{ comment.created_time | date:"Y-m-d H:i:s" }}
                </span> 时说：
            </p>
            <pre style="font-family: inherit; font-size: 1em;">
        {{ comment.body }}</pre>
        {% endfor %}
    </div>
{% endblock title %}

templates/article_list.html
{% extends 'base.html' %}
    {% block content %}

        <div class="container border" style="height: 700px">
        <p id="currentPath">您当前的位置是:</p>
        <script>
            // 获取当前页面的路径部分
            var currentPath = window.location.pathname;
            var parts = currentPath.split("/").filter(part => part !== ""); // 将字符串分割成数组，然后过滤掉空字符串
            var firstPart = parts[0];
            var secondPart = parts[1];
            if (firstPart === "article"){
                firstPart = "首页"
            }
            if(secondPart === "happen"){
                secondPart = "近视的发生"
            }
             if(secondPart === "prevent"){
                secondPart = "近视的预防"
            }
             if(secondPart === "appliance"){
                secondPart = "防近视器材"
            }
              if(secondPart === "news"){
                secondPart = "近视的要闻"
            }
               if(secondPart === "about"){
                secondPart = "关于我们"
            }
            // 显示路径
            document.getElementById("currentPath").textContent = "您当前的位置是:"+firstPart + ">" + secondPart;
        </script>
            {#对文章进行列表展示#}
            <ul class="list-group list-group-flush">
                {% for article in articles %}
                    <li style="margin: 5px 30px">
                     <!-- 同样改写 href -->
                        <a href="{% url 'article:article_detail_show' article.id %}"style="color: #000000;">{{ article.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <!-- 页码导航 -->
        <div class="pagination row">
            <div class="m-auto">
                <span class="step-links">
                    <!-- 如果不是第一页，则显示上翻按钮 -->
                    {% if articles.has_previous %}
                        <a href='?page=1' class="btn btn-secondary">首页</a>
                         <a href="?page={{ article_list.previous_page_number }}"
                           class="btn btn-secondary">
                            上一页
                        </a>
                        <a href="?page={{ article_list.previous_page_number }}"
                           class="btn btn-secondary"
                        >
                            {{ articles.previous_page_number }}
                        </a>
                    {% endif %}
                    <!-- 当前页面 -->
                    <span class="current btn btn-danger btn-lg">
                        {{ articles.number }}
                    </span>

                    <!-- 如果不是最末页，则显示下翻按钮 -->
                    {% if articles.has_next %}
                        <a href="?page={{ articles.next_page_number }}"
                           class="btn btn-secondary">
                            {{ articles.next_page_number }}
                        </a>
                          <a href="?page={{ articles.next_page_number }}"
                           class="btn btn-secondary">
                            下一页
                        </a>
                        <a href='?page={{ articles.num_pages }}'
                         class="btn btn-secondary">尾页</a>
                    {% endif %}

                </span>
            </div>
        </div>
        {% endblock %}

templates/base.html
<!--
    载入静态文件
    使用 Django 3 学习的读者改为
-->
{% load static %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

    <head>
        <!-- 网站采用的字符编码 -->
        <meta charset="utf-8">
        <!-- 预留网站标题的位置 -->
        <title>{% block title %}{% endblock %}</title>
        <!-- 引入bootstrap的css文件 -->
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    </head>

    <body>
        <!-- 导航栏 -->
        <div id = 'header'>
            {% include 'header.html' %}
        </div>
         <!-- 预留具体页面的位置 -->
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
         <!-- 注脚 -->
        <div id="footer">
            {% include 'footer.html' %}
        </div>

        <!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
        <script src="{% static 'jquery/jquery-3.7.0.js' %}"></script>

         <!-- 引入layer.js -->
        <script src="{% static 'layer/layer.js' %}"></script>

        <!--
            popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
            在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
            教程采用本地引入是为了让读者了解静态文件本地部署的流程。
        -->
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

        <!-- 引入bootstrap的js文件 -->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    </body>

</html>

templates/content.html
<div>
    <h1>Content Area</h1>
    <p>{{ content_data }}</p>
</div>

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <!-- 写文章表单 -->
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <!-- 提交文章的表单 -->
                <form method="post" action="">
                    <!-- Django中需要POST数据的地方都必须有csrf_token -->
                    {% csrf_token %}
                    <!-- 文章标题 -->
                    <div class="form-group">
                        <!-- 标签 -->
                        <label for="title">文章标题</label>
                        <!-- 文本框 -->
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <!-- 文章栏目 -->
                    <div class="form-group">
                        <label for="column">栏目</label>
                        <select class="form-control"
                                id="column"
                                name="column"
                        >
                                <option value="none">请选择栏目..</option>
                            {% for column in columns %}
                                <option value="{{ column.id }}">{{ column }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <!-- 文章正文 -->
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        <!-- 文本区域 -->
                        <textarea type="text" class="form-control" id="body" name="content" rows="12"></textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>

</body>
</html>

templates/editor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Markdown Editor</title>
    <link rel="stylesheet" href="{% static 'mdeditor/css/editormd.css' %}"/>
     <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>
<style>
    #center {
        margin-top: 5%;
        width: 96%;
        height: 96%;
        border: 1px;
    }

    img {
        margin: auto;
        margin-left: 30%;
        height: 40%;
        width: 40%;
        position: relative;
        top: 10%;
    }

    input {

        width: 85%;
        height: 30px;
        border-width: 2px;
        border-radius: 5px;
        border-color: #00c4ff;
        border-bottom-color: #2C7EEA;
        color: #586e75;
        font-size: 15px;

    }

    button {
        width: 10%;
        height: 35px;
        border-width: 0px;
        margin-left: 3%;
        border-radius: 10px;
        background: #1E90FF;
        cursor: pointer;
        outline: none;
        font-family: Microsoft YaHei;
        color: white;
        font-size: 17px;
    }
        button:hover {
        background-color: #1E90FF;
        box-shadow: 0 4px 0 powderblue;
    }
</style>
<body>
{% csrf_token %}
<form method="post" action="." enctype="multipart/form-data">
    <div class="form-group">
        <div>
            <input type="text" name="title"  value="{{ article.title }}" placeholder="请输入文章标题" required>
            <button type="submit" id="submit">发布文章</button>
        </div>
        <br>
        <!-- 文章栏目 -->
    <div class="form-group">
        <label for="column">栏目</label>
    <div class="row">
        <div class="col-10">
             <select class="form-control"
                id="column"
                name="column">
                <option value="none">{{ type }}</option>
                {% for column in columns %}
                    <option value="{{ column.title }}">{{ column }}</option>
                {% endfor %}
        </select>
        </div>
    </div>
    </div>
        <br>
        <div id="editormd">
            {% csrf_token %}
            <textarea style="display:none;" name="content" >{{ article.content }}</textarea>
        </div>
    </div>

</form>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static 'mdeditor/editormd.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        var editor = editormd("editormd", {
            width  : "100%",
            height : "800",
            path   : "{% static 'mdeditor/lib/' %}",
            placeholder: "请开始你的书写之旅",
            //增加图片上传配置
            imageUpload    : true,
            imageFormats   : ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL : "/upload/",//图片上传的地址（在你的项目里面的路由）
            required:true,
            saveHTMLToTextarea : true,
            taskList: true,
            tocm: true,
            tex: true,                   // 开启科学公式TeX语言支持，默认关闭
            flowChart: true,             // 开启流程图支持，默认关闭
            sequenceDiagram: true,       // 开启时序/序列图支持，默认关闭,

        });

    });
    var blogeditor = document.getElementById("blogeditor");
    blogeditor.required = true;
    var button = document.getElementById("submit");
    button.addEventListener("click",()=>{
        if(blogeditor.value==''){
            alert("博客内容不能为空");
        }
    });
</script>
</body>
</html>

templates/footer.html
{% load static  %}
<!-- Footer -->
<footer class="py-3"style="background-color: #c3c3c3;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4 text-center" >
                <a href="" style="color: #0a001f">网站声明</a>
                <a href="" style="color: #0a001f">|关于我们|</a>
                <a href="" style="color: #0a001f">联系我们</a>
                <hr color="blue">
                <a href=""style="color: #0a001f">XX科技网</a>
            </div>
        </div>
    </div>
</footer>

templates/header.html
{% load static %}
<!-- 引入bootstrap的css文件 -->
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<div style="background-color: #9d9d9d">
    <h6 style="display: inline;margin-left: 200px">欢迎访问科技网！</h6>
    <a href="{% url "userprofile:register"%}?next={{ request.path }}" style="margin-left: 900px">注册</a>
    <span>|</span>
    <a href="{% url 'userprofile:login'%}?next={{ request.path }}">登录</a>
</div>
 <img src="static/header.png" alt="">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark "style="background-color: #1476c1;">
  <div class=" container">
    <!-- 导航入口 -->
    <div >
       <ul class="nav nav-pills" style="border-bottom-left-radius: 100px">
         <div class="nav-item mr-lg-5">
                <a href="/" style="color: #FFFFFF;">首页</a>
         </div>
         <div class="nav-item mr-lg-5">
              <a href="{% url 'article:happen' %}" style="color: #FFFFFF;margin-left: 10px">|&nbsp;&nbsp;&nbsp;&nbsp;近视的发生&nbsp;&nbsp;&nbsp;&nbsp;|</a>
          </div>
         <div class="nav-item mr-lg-5">
              <a href="{% url 'article:prevent' %}" style="color: #FFFFFF;margin-left: 10px">|&nbsp;&nbsp;&nbsp;&nbsp;近视的预防&nbsp;&nbsp;&nbsp;&nbsp;|</a>
          </div>
         <div class="nav-item mr-lg-5">
              <a href="{% url 'article:appliance' %}" style="color: #FFFFFF;margin-left: 10px">|&nbsp;&nbsp;&nbsp;&nbsp;防近视器材&nbsp;&nbsp;&nbsp;&nbsp;|</a>
          </div>
         <div class="nav-item mr-lg-5">
              <a href="{% url 'article:news' %}" style="color: #FFFFFF;margin-left: 10px">|&nbsp;&nbsp;&nbsp;&nbsp;防近视要闻&nbsp;&nbsp;&nbsp;&nbsp;|</a>
          </div>
           <div class="nav-item mr-lg-5">
              <a href="{% url 'article:about' %}" style="color: #FFFFFF;margin-left: 10px">|&nbsp;&nbsp;&nbsp;&nbsp;关于我们&nbsp;&nbsp;&nbsp;&nbsp;|</a>
          </div>
        </ul>
    </div>
      {#  导航栏的右边提示框#}
{#    {% if user.is_authenticated %}#}
{#        <span class="navbar-text">欢迎您：</span>#}
{#        <span class="navbar-text">{{ user.username }}</span>#}
{#        {% include 'setting_nav.html' %}#}
{#    {% else %}#}
{#      <a href="{% url 'userprofile:login' %}?next={{ request.path }}"><button type="button" class="btn btn-primary">请登录</button></a>#}
{#    {% endif %}#}
  </div>
</nav>

templates/home_list.html
<div class="row">
    {#对文章进行列表展示#}
    <ul class="list-group list-group-flush">
        {% for article in article_sub_list %}
            <li  style="margin: 5px 30px">
             <!-- 同样改写 href -->
                <a href="{% url 'article:article_detail_show' article.id %}"style="color: #000000;">{{ article.title }}</a>
            </li>
        {% endfor %}
    </ul>

</div>

templates/setting_nav.html
<!-- Example single danger button -->
<div class="btn-group"style="margin-left: 100px">
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    设置
  </button>
  <div class="dropdown-menu">
      <a class="dropdown-item" href="#">个人资料修改</a>
      <a class="dropdown-item" href="{% url 'article:article_create' %}">写发布</a>
      <a class="dropdown-item" href="{% url "userprofile:logout" %}?next={{ request.path }}">退出登录</a>
  </div>
</div>

templates/slide_page.html
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="static/pic1.png"  height="300px" width="600px" alt="...">
    </div>
    <div class="carousel-item">
      <img src="static/pic1.png" height="300px" width="600px" alt="...">
    </div>
  </div>
 <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </button>
</div>

templates/small_slide_page.html
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="static/pic1.png" style="padding: 0;margin: 0" height="200px" alt="...">
    </div>
    <div class="carousel-item">
      <img src="static/pic1.png" style="padding: 0;margin: 0" height="200px" alt="...">
    </div>
  </div>
 <button class="carousel-control-prev" type="button" data-target="#carouselExampleControls" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-target="#carouselExampleControls" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </button>
</div>